version: '3.1'

services:

  my_mariadb_service:
    image: mariadb
    restart: always
    volumes:
      - './mariadb_data:/var/lib/mysql'
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: my_root_pass
    ports:
      - '3306:3306'
